### ISSUE TITLE
Adding letter to DP

### ISSUE THREAD

**Issue by Emigrowscredit** [destevez0610/mustard-app#16]
### Description of the bug

When uploading the letters into the software, it doesn’t categorize them correctly under the name of the bureau it’s supposed to be even after I select the bureau name. 

### Steps to reproduce

Step 1. 
Step 2.
Step 3.

### Screenshots

I have a video but it’s not letting me upload it.  Let me know how to proceed

**Comment by markishere16** [comment]
Hi @Emigrowscredit can you record a loom video? and which company you are doing that. Thank you

**Comment by Emigrowscredit** [comment]
For convenient consulting and ok I will. Send it later today
